{% set name = "anaconda-anon-usage" %}
{% set version = "0.3.0" %}
{% set sha256 = "58156aae02cd77d844b0d93192c0776459d71ed70a45c2a9d776cbc3b0afebab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [py<=36]
  script_env:
   - NEED_SCRIPTS=no   # [variant=="plugin"]
   - NEED_SCRIPTS=yes  # [variant=="patch"]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    - conda >=23.7  # [variant=="plugin"]
    - conda >=4.11,<23.7   # [variant=="patch"]

test:
  source_files:
    - tests
  imports:
    - anaconda_anon_usage
  commands:
    - export ANACONDA_ANON_USAGE_DEBUG=1  # [unix]
    - set ANACONDA_ANON_USAGE_DEBUG=1  # [win]
    - conda info
    - python -m anaconda_anon_usage.install --status  # [variant=="patch"]
    - python tests/test_config.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-anon-usage
  summary: basic anonymous telemetry for conda clients
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Anaconda-Platform/anaconda-anon-usage/
  doc_url: https://github.com/Anaconda-Platform/anaconda-anon-usage/
  description: |
        This package augments the request header data that conda delivers
        to package servers during index and package requests. Specifically,
        three randomly generated tokens are appended to the "user agent"
        that Conda already sends with each request.
