{% set name = "anaconda-anon-usage" %}
{% set version = "0.2.0" %}
{% set sha256 = "be40c23ae3f5e7b45782282e98e019e1b31d93536a612259393fec81f5f52a4b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script_env:
   - NEED_SCRIPTS=no   # [variant=="plugin"]
   - NEED_SCRIPTS=yes  # [variant=="patch"]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=23.7  # [variant=="plugin"]
    - conda>=22.11,<23.7   # [variant=="patch"]

test:
  source_files:
    - tests
  commands:
    - export ANACONDA_ANON_USAGE_DEBUG=1  # [unix]
    - set ANACONDA_ANON_USAGE_DEBUG=1  # [win]
    - conda info
    - python -m anaconda_anon_usage.install --status  # [variant=="patch"]
    - python tests/test_config.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-anon-usage
  summary: basic anonymous telemetry for conda clients
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/Anaconda-Platform/anaconda-anon-usage/
  doc_url: https://github.com/Anaconda-Platform/anaconda-anon-usage/
